apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: viglesiasce/sample-app-backend-dev
    workspace: cmd/backend
    kaniko: {}
  - imageName: viglesiasce/sample-app-frontend-dev
    workspace: cmd/frontend
deploy:
  kustomize:
    kustomizePath: k8s/dev/
