kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend
spec:
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: backend
      labels:
        env: dev
    spec:
      containers:
      - name: backend
        image: sample-app-backend-dev
        env:
        - name: VERSION
          value: dev
